### ISSUE TITLE
External: Error when parsing websites with bad SSL Certificate

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#117]
Debug message:

```
[2022-03-11 09:15:26,637] *** requested https://wp3.opted.eu/endpoint/new/submit: ERROR in routes: Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
   conn = connection.create_connection(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
   raise err
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
   sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
   httplib_response = self._make_request(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
   self._validate_conn(conn)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
   conn.connect()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
   conn = self._new_conn()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
   raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd7a1aac6d0>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
   resp = conn.urlopen(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
   retries = retries.increment(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
   raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[www.faktum-magazin.de](http://www.faktum-magazin.de/)', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd7a1aac6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/endpoints/routes.py", line 113, in submit
   sanitizer = SourceSanitizer(
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 73, in __init__
   self.process_website()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 306, in process_website
   self.fetch_feeds()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 1137, in fetch_feeds
   sitemaps = find_sitemaps(self.newsource['name'])
 File "/home/ava/wp3inventory/flaskinventory/add/external.py", line 94, in find_sitemaps
   r = requests.get(site, headers=headers)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 75, in get
   return request('get', url, params=params, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 61, in request
   return session.request(method=method, url=url, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
   resp = self.send(prep, **send_kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
   r = adapter.send(request, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[www.faktum-magazin.de](http://www.faktum-magazin.de/)', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd7a1aac6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

````
[2022-03-11 10:51:24,244] *** requested https://wp3.opted.eu/endpoint/new/submit: ERROR in routes: Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
   httplib_response = self._make_request(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
   self._validate_conn(conn)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
   conn.connect()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
   self.sock = ssl_wrap_socket(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
   ssl_sock = _ssl_wrap_socket_impl(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
   return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
 File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
   return self.sslsocket_class._create(
 File "/usr/lib/python3.8/ssl.py", line 1040, in _create
   self.do_handshake()
 File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
   self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
   resp = conn.urlopen(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
   retries = retries.increment(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
   raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[freie-medien.tv](http://freie-medien.tv/)', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/add/external.py", line 189, in parse_meta
   r = requests.get(site, headers=headers)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 75, in get
   return request('get', url, params=params, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 61, in request
   return session.request(method=method, url=url, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
   resp = self.send(prep, **send_kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
   r = adapter.send(request, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
   raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[freie-medien.tv](http://freie-medien.tv/)', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
   httplib_response = self._make_request(
[10:51](https://cclteamgruppe.slack.com/archives/C02MJ6X1ZSL/p1646992284428279)
File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
   self._validate_conn(conn)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
   conn.connect()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
   self.sock = ssl_wrap_socket(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
   ssl_sock = _ssl_wrap_socket_impl(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
   return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
 File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
   return self.sslsocket_class._create(
 File "/usr/lib/python3.8/ssl.py", line 1040, in _create
   self.do_handshake()
 File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
   self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
   resp = conn.urlopen(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
   retries = retries.increment(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
   raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[freie-medien.tv](http://freie-medien.tv/)', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 523, in resolve_website
   urls, names = parse_meta(self.json.get('name'))
 File "/home/ava/wp3inventory/flaskinventory/add/external.py", line 191, in parse_meta
   r = requests.get(site.replace('https', 'http'))
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 75, in get
   return request('get', url, params=params, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 61, in request
   return session.request(method=method, url=url, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
   resp = self.send(prep, **send_kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
   history = [resp for resp in gen]
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
   history = [resp for resp in gen]
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
   resp = self.send(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
   r = adapter.send(request, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
   raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='[freie-medien.tv](http://freie-medien.tv/)', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/endpoints/routes.py", line 113, in submit
   sanitizer = SourceSanitizer(
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 73, in __init__
   self.process_website()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 273, in process_website
   self.resolve_website()  # check if website exists / parse url
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 525, in resolve_website
   raise InventoryValidationError(
flaskinventory.add.validators.InventoryValidationError: Could not resolve website! URL provided does not exist: https://freie-medien.tv/
```

**Comment by mrwunderbar666** [comment]
Cases: `http://www.faktum-magazin.de/` and `https://freie-medien.tv/`
