### ISSUE TITLE
Add: autocoding organizations - Query Sanitization 

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#119]
Adding a new source with a new organization causes an error if the organization name contains quotation marks `"`:

Example to reproduce: `KVV "konkret" Vertriebsgesellschaft für Druck- und andere Medien GmbH & Co. KG`

```
[2022-03-18 11:13:18,077]  *** requested https://wp3.opted.eu/endpoint/new/submit: ERROR in routes: Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/endpoints/routes.py", line 113, in submit
   sanitizer = SourceSanitizer(
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 73, in __init__
   self.process_website()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 281, in process_website
   self.parse_org()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 898, in parse_org
   res = dgraph.query(query)
 File "/home/ava/wp3inventory/flaskinventory/flaskdgraph/client.py", line 137, in query
   res = self.connection.txn(read_only=True).query(query_string)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 62, in query
   return self.do_request(req, timeout=timeout, metadata=metadata, credentials=credentials)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 126, in do_request
   self._common_except_mutate(query_error)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 229, in _common_except_mutate
   raise error
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 102, in do_request
   response = self._dc.query(request, timeout=timeout,
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/client_stub.py", line 60, in query
   return self.stub.Query(req, timeout=timeout, metadata=metadata,
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
   return _end_unary_response_blocking(state, call, False, None)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
   raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNKNOWN
    details = "line 1 column 25: Expected comma or language but got: konkret"
    debug_error_string = "{"created":"@1647598398.076195092","description":"Error received from peer ipv4:127.0.0.1:9080","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"line 1 column 25: Expected comma or language but got: konkret","grpc_status":2}"
```

**Comment by mrwunderbar666** [comment]
done #127
