### ISSUE TITLE
New Source: Error in <related>! UID specified does not match constraint, UID is not a ['Source']!: uid <0x123> <dgraph.type> <Organization>

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#147]
When adding a new source: adding a new related source and a new organization with the exact same name causes this error:

```
[2022-05-16 11:21:03,886] 123 requested https://wp3.opted.eu/endpoint/new/submit: ERROR in routes: Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/endpoints/routes.py", line 119, in submit
   sanitizer = Sanitizer.edit(request.json, dgraph_type=Source)
 File "/home/ava/wp3inventory/flaskinventory/main/sanitizer.py", line 129, in edit
   return cls(data, is_upsert=True, dgraph_type=dgraph_type, entry_review_status=entry_review_status, fields=edit_fields, **kwargs)
 File "/home/ava/wp3inventory/flaskinventory/main/sanitizer.py", line 77, in __init__
   self._parse()
 File "/home/ava/wp3inventory/flaskinventory/main/sanitizer.py", line 268, in _parse
   node_data, data_node = item.validate(self.data[key], self.entry_uid, facets=facets)
 File "/home/ava/wp3inventory/flaskinventory/flaskdgraph/dgraph_types.py", line 622, in validate
   n2d, d2n = super().validate(item, node, facets)
 File "/home/ava/wp3inventory/flaskinventory/flaskdgraph/dgraph_types.py", line 575, in validate
   raise InventoryValidationError(
flaskinventory.errors.InventoryValidationError: Error in <related>! UID specified does not match constraint, UID is not a ['Source']!: uid <0x22318> <dgraph.type> <Organization>
```

Look into appending a random string to `NewID()` (e.g. `_:name_of_new_entity_random123`) then dgraph statement should be error free

**Comment by mrwunderbar666** [comment]
Add better / clearer description of error. Include name and unique_name of entity
