### ISSUE TITLE
View Rejected by uid causes 500 error

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#225]
needs proper handling of rejected types (these dont have a uid)

Related to #223 (need some unit tests for rejected entries)

Regression caused by #174

```
Traceback (most recent call last):
  File "wp3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "wp3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "wp3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "wp3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "wp3inventory/flaskinventory/view/routes.py", line 43, in view_uid
    unique_name = dgraph.get_unique_name(uid)
  File "wp3inventory/flaskinventory/flaskdgraph/client.py", line 175, in get_unique_name
    return data['q'][0]['unique_name']
KeyError: 'unique_name'
```

**Comment by mrwunderbar666** [comment]
closed with #226
