### ISSUE TITLE
Edit Source: Glitch AttributeError("'UID' object has no attribute 'get'")

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#73]
```
Traceback (most recent call last):
File "/home/ava/wp3inventory/flaskinventory/edit/routes.py" line 147, in source
sanitizer = EditSourceSanitizer(
File "/home/ava/wp3inventory/flaskinventory/edit/sanitize.py", line 304, in __init__
    nquads += dict_to_nquad(subunit)
  File "/home/ava/wp3inventory/flaskinventory/flaskdgraph/dgraph_types.py", line 173, in dict_to_nquad
    if d.get(\'uid\'):
AttributeError: \'UID\' object has no attribute \'get\'
',)
```

**Comment by mrwunderbar666** [comment]
Error occurs when editing sources
