### ISSUE TITLE
Add: external.parse_meta() - SSL Error

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#74]
Getting meta info of websites with expired SSL certificate fails. Add failsafe for `SSLError`

```
[2021-12-16 16:48:57,517] 81.217.181.91 requested https://wp3.opted.eu/endpoint/new/submit: ERROR in routes: Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
   httplib_response = self._make_request(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
   self._validate_conn(conn)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
   conn.connect()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 469, in connect
   _match_hostname(cert, self.assert_hostname or server_hostname)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connection.py", line 542, in _match_hostname
   match_hostname(cert, asserted_hostname)
 File "/usr/lib/python3.8/ssl.py", line 416, in match_hostname
   raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname 'www.ennsseiten.at' doesn't match either of '*.kasserver.com', 'kasserver.com'",)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
   resp = conn.urlopen(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
   retries = retries.increment(
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
   raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.ennsseiten.at', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'www.ennsseiten.at' doesn't match either of '*.kasserver.com', 'kasserver.com'")))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 491, in resolve_website
   urls, names = parse_meta(self.json.get('name'))
 File "/home/ava/wp3inventory/flaskinventory/add/external.py", line 177, in parse_meta
   r = requests.get(site, headers=headers)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 75, in get
   return request('get', url, params=params, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/api.py", line 61, in request
   return session.request(method=method, url=url, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
   resp = self.send(prep, **send_kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
   r = adapter.send(request, **kwargs)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
   raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.ennsseiten.at', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'www.ennsseiten.at' doesn't match either of '*.kasserver.com', 'kasserver.com'")))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/endpoints/routes.py", line 110, in submit
   sanitizer = SourceSanitizer(
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 68, in __init__
   self.process_website()
File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 256, in process_website
   self.resolve_website()  # check if website exists / parse url
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 493, in resolve_website
   raise InventoryValidationError(
flaskinventory.add.validators.InventoryValidationError: Could not resolve website! URL provided does not exist: www.ennsseiten.at
```

**Comment by mrwunderbar666** [comment]
error has not occurred since. Closing this for now
