### ISSUE TITLE
Edit: Choices of related sources should filter out rejected entries

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#80]
If a source is edited the choices for related sources also loads rejected entries. This causes an error, because rejected entries do not have a unique name anymore.

Full error log:

```
[2022-01-03 12:19:28,529] requested https://wp3.opted.eu/edit/source/uid/0xc481: ERROR in app: Exception on /edit/source/uid/0xc481 [GET]
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
   return func(*args, **kwargs)
 File "/home/ava/wp3inventory/flaskinventory/edit/routes.py", line 189, in source
   choices = [(subval['uid'], subval['unique_name'])
 File "/home/ava/wp3inventory/flaskinventory/edit/routes.py", line 189, in <listcomp>
   choices = [(subval['uid'], subval['unique_name'])
KeyError: 'unique_name'
```

**Comment by mrwunderbar666** [comment]
patched for now, but not very elegant
