### ISSUE TITLE
Add: audience size copies sold -> coerce to int

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#81]
When users add audience size manually, sometimes they include periods or commas to separate thousands. This causes an error, as these strings cannot be converted to int() automatically.

- Add a try / except block to the corresponding section in the Sanitize Class
- figure out a way of reliably coercing strings to ints
- add a more descriptive error message to the user

Full error log:

```
[2022-01-04 14:59:26,282] requested https://wp3.opted.eu/endpoint/new/submit: ERROR in routes: Traceback (most recent call last):
 File "/home/ava/wp3inventory/flaskinventory/endpoints/routes.py", line 110, in submit
   sanitizer = SourceSanitizer(
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 66, in __init__
   self.process_print()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 202, in process_print
   self.parse_audience_size()
 File "/home/ava/wp3inventory/flaskinventory/add/sanitize.py", line 728, in parse_audience_size
   facets = {'copies_sold': int(
ValueError: invalid literal for int() with base 10: '150.000'
```

**Comment by mrwunderbar666** [comment]
Javascript & Browser already validate against proper integer input. Probably an issue that can be caused by outdated browsers. Added a better error message & a try / except block
