### ISSUE TITLE
View: view/source/uid/<uid> route should only accept uids

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#82]
When the route `view/source/uid/<uid>` receives a string that doesn't match a UID pattern, it should return 404.

Full error log:

```
[2022-01-04 15:38:13,885] requested https://wp3.opted.eu/view/source/uid/Wikipedia: ERROR in app: Exception on /view/source/uid/Wikipedia [GET]
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/home/ava/wp3inventory/flaskinventory/view/routes.py", line 97, in view_source
   unique_item = get_source(uid=uid)
 File "/home/ava/wp3inventory/flaskinventory/view/dgraph.py", line 38, in get_source
   data = dgraph.query(query)
 File "/home/ava/wp3inventory/flaskinventory/flaskdgraph/client.py", line 135, in query
   res = self.connection.txn(read_only=True).query(query_string)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 62, in query
   return self.do_request(req, timeout=timeout, metadata=metadata, credentials=credentials)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 126, in do_request
   self._common_except_mutate(query_error)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 229, in _common_except_mutate
   raise error
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/txn.py", line 102, in do_request
   response = self._dc.query(request, timeout=timeout,
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/pydgraph/client_stub.py", line 60, in query
   return self.stub.Query(req, timeout=timeout, metadata=metadata,
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
   return _end_unary_response_blocking(state, call, False, None)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
   raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNKNOWN
    details = "Some variables are used but not defined
Defined:[]
Used:[Wikipedia]
"
    debug_error_string = "{"created":"@1641307093.885517376","description":"Error received from peer ipv4:127.0.0.1:9080","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Some variables are used but not defined\nDefined:[]\nUsed:[Wikipedia]\n","grpc_status":2}"
```

**Comment by mrwunderbar666** [comment]
related to #83 and fixed with d6ab4ec1d5dcfa8065f6ef4b45af7cdcee911a08
