### ISSUE TITLE
View: Arbitrary UIDs cause server error

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/wp3inventory#83]
DGraph always returns a value when a UID is queried, regardless whether the entry exists. This leads to 500 errors when using routes that directly query UIDs:

e.g.: `view/source/uid/0xea7b123123123123` causes 500 error instead of 404

**Comment by mrwunderbar666** [comment]
triggered again, probably by bot or malicious attempt:

```
[2022-01-20 01:18:19,446]  requested https://wp3.opted.eu/view?uid=0xeace: ERROR in app: Exception on /view [GET]
Traceback (most recent call last):
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
   return self.finalize_request(rv)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
   response = self.make_response(rv)
 File "/home/ava/environments/wp3/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
   raise TypeError(
TypeError: The view function for 'view.view_uid' did not return a valid response. The function either returned None or ended without a return statement.
```
